import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Supply Chain Intelligence System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          {children}
          <Toaster
            richColors
            style={{
              background: "#0f172a",
              color: "#f8fafc",
              borderRadius: "12px",
              padding: "12px",
              boxShadow: "0 20px 40px rgba(0,0,0,0.35)",
              fontWeight: 500,
            }}
            position="bottom-right"
          />
        
        </ThemeProvider>
      </body>
    </html>
  );
}
