import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/lib/AuthContext";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Supply Chain Intelligence System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className}  antialiased`}
      >
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <AuthProvider>
                {children}
              </AuthProvider>
          
          <Toaster
            richColors
            style={{
              background: "#0f172a",
              color: "#f8fafc",
              borderRadius: "12px",
              padding: "12px",
              boxShadow: "0 20px 40px rgba(0,0,0,0.35)",
              fontWeight: 500,
            }}
            position="bottom-right"
          />
        
        </ThemeProvider>
      </body>
    </html>
  );
}
